export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";
export const UPDATE_DROPDOWN_VALUE = "UPDATE_DROPDOWN_VALUE";
export const FETCH_REPOS = "FETCH_REPOS";
export const FETCH_USERS = "FETCH_USERS";
export const HANDLE_FETCH_STARTED = "HANDLE_FETCH_STARTED";
export const HANDLE_FETCH_SUCCESS = "HANDLE_FETCH_SUCCESS";
export const HANDLE_FETCH_FAILURE = "HANDLE_FETCH_FAILURE";
export const FETCH_USERS_DEEPER = "FETCH_USERS_DEEPER";
export const CLEAR_USERS = "CLEAR_USERS";
export const CLEAR_REPOS = "CLEAR_REPOS";


